### ISSUE TITLE
PYPI

### ISSUE THREAD

**Issue by SunnyXu** [markur4/plotastic#2]
(1) Please note that the figures/plots on the PYPI page (https://pypi.org/project/plotastic/) are not shown.
(2) The package indeed works with Python 3.11. However, is this Python package only applicable to 3.11 or did you perform it with Python 3.11 only?

**Comment by markur4** [comment]
Thanks for pointing these out!
(1) For tables, I've decided to exclude them from PyPI, since they weren't displaying correctly. For figures/plots, I decided to exclude them at early versions, because at that time, I was changing the image directories and the links would keep breaking. I plan on displaying figures/plots in PyPI in later versions.

(2) plotastic runs on python==3.11, since I haven't tested older versions. I could run plotastic on older versions to see which is the minimum version.
